---
# tasks file for java-install-from-repo
- name: ensure required packages are installed for Java 8
  apt_repository:
    repo:     'ppa:webupd8team/java'
    update_cache: yes

- name: Autoaccept license for Java
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Update APT package cache
  apt: update_cache=yes

- name: Install Java 8
  apt:
    name: oracle-java8-installer
    state: latest
    install_recommends: yes

- name: Set Java 8 Env
  apt:
    name: oracle-java8-set-default
    state: latest 
    install_recommends: yes
