---
# tasks file for java-install-from-repo
- name: ensure required packages are installed for Java 7
  apt_repository:
    repo:     'ppa:webupd8team/java'
    update_cache: yes

- name: Autoaccept license for Java
  action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Update APT package cache
  action: apt update_cache=yes

- name: Install Java 7
  action: apt pkg=oracle-java7-installer state=latest install_recommends=yes

- name: Set Java 7 Env
  action: apt pkg=oracle-java7-set-default state=latest install_recommends=yes